/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as HearingAidsRouteImport } from './routes/hearing-aids'
import { Route as HearingLossRouteImport } from './routes/hearing-loss'
import { Route as HearingTestRouteImport } from './routes/hearing-test'
import { Route as TestimonialsRouteImport } from './routes/testimonials'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const HearingAidsRoute = HearingAidsRouteImport.update({
  id: '/hearing-aids',
  path: '/hearing-aids',
  getParentRoute: () => rootRouteImport,
} as any)
const HearingLossRoute = HearingLossRouteImport.update({
  id: '/hearing-loss',
  path: '/hearing-loss',
  getParentRoute: () => rootRouteImport,
} as any)
const HearingTestRoute = HearingTestRouteImport.update({
  id: '/hearing-test',
  path: '/hearing-test',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/hearing-aids': typeof HearingAidsRoute
  '/hearing-loss': typeof HearingLossRoute
  '/hearing-test': typeof HearingTestRoute
  '/testimonials': typeof TestimonialsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/hearing-aids': typeof HearingAidsRoute
  '/hearing-loss': typeof HearingLossRoute
  '/hearing-test': typeof HearingTestRoute
  '/testimonials': typeof TestimonialsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/hearing-aids': typeof HearingAidsRoute
  '/hearing-loss': typeof HearingLossRoute
  '/hearing-test': typeof HearingTestRoute
  '/testimonials': typeof TestimonialsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/hearing-aids'
    | '/hearing-loss'
    | '/hearing-test'
    | '/testimonials'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/hearing-aids'
    | '/hearing-loss'
    | '/hearing-test'
    | '/testimonials'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/hearing-aids'
    | '/hearing-loss'
    | '/hearing-test'
    | '/testimonials'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  HearingAidsRoute: typeof HearingAidsRoute
  HearingLossRoute: typeof HearingLossRoute
  HearingTestRoute: typeof HearingTestRoute
  TestimonialsRoute: typeof TestimonialsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hearing-aids': {
      id: '/hearing-aids'
      path: '/hearing-aids'
      fullPath: '/hearing-aids'
      preLoaderRoute: typeof HearingAidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hearing-loss': {
      id: '/hearing-loss'
      path: '/hearing-loss'
      fullPath: '/hearing-loss'
      preLoaderRoute: typeof HearingLossRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hearing-test': {
      id: '/hearing-test'
      path: '/hearing-test'
      fullPath: '/hearing-test'
      preLoaderRoute: typeof HearingTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  HearingAidsRoute: HearingAidsRoute,
  HearingLossRoute: HearingLossRoute,
  HearingTestRoute: HearingTestRoute,
  TestimonialsRoute: TestimonialsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
